-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dataflow_parent_loop_1 is
port (
    img_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    img_ce0 : OUT STD_LOGIC;
    img_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    img_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    img_we0 : OUT STD_LOGIC;
    img_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    img_ce1 : OUT STD_LOGIC;
    img_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    img_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    img_we1 : OUT STD_LOGIC;
    h_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    h_ce0 : OUT STD_LOGIC;
    h_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    h_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    h_we0 : OUT STD_LOGIC;
    h_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    h_ce1 : OUT STD_LOGIC;
    h_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    h_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    h_we1 : OUT STD_LOGIC;
    c_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    c_ce0 : OUT STD_LOGIC;
    c_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    c_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    c_we0 : OUT STD_LOGIC;
    c_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    c_ce1 : OUT STD_LOGIC;
    c_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    c_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    c_we1 : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC );
end;


architecture behav of dataflow_parent_loop_1 is 
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv5_1C : STD_LOGIC_VECTOR (4 downto 0) := "11100";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";

    signal dataflow_in_loop_lst_U0_img_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal dataflow_in_loop_lst_U0_img_ce0 : STD_LOGIC;
    signal dataflow_in_loop_lst_U0_img_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_lst_U0_img_we0 : STD_LOGIC;
    signal dataflow_in_loop_lst_U0_img_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal dataflow_in_loop_lst_U0_img_ce1 : STD_LOGIC;
    signal dataflow_in_loop_lst_U0_img_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_lst_U0_img_we1 : STD_LOGIC;
    signal dataflow_in_loop_lst_U0_h_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal dataflow_in_loop_lst_U0_h_ce0 : STD_LOGIC;
    signal dataflow_in_loop_lst_U0_h_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_lst_U0_h_we0 : STD_LOGIC;
    signal dataflow_in_loop_lst_U0_h_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal dataflow_in_loop_lst_U0_h_ce1 : STD_LOGIC;
    signal dataflow_in_loop_lst_U0_h_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_lst_U0_h_we1 : STD_LOGIC;
    signal dataflow_in_loop_lst_U0_c_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal dataflow_in_loop_lst_U0_c_ce0 : STD_LOGIC;
    signal dataflow_in_loop_lst_U0_c_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_lst_U0_c_we0 : STD_LOGIC;
    signal dataflow_in_loop_lst_U0_c_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal dataflow_in_loop_lst_U0_c_ce1 : STD_LOGIC;
    signal dataflow_in_loop_lst_U0_c_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_lst_U0_c_we1 : STD_LOGIC;
    signal dataflow_in_loop_lst_U0_ap_start : STD_LOGIC;
    signal dataflow_in_loop_lst_U0_ap_done : STD_LOGIC;
    signal dataflow_in_loop_lst_U0_ap_ready : STD_LOGIC;
    signal dataflow_in_loop_lst_U0_ap_idle : STD_LOGIC;
    signal dataflow_in_loop_lst_U0_ap_continue : STD_LOGIC;
    signal ap_sync_continue : STD_LOGIC;
    signal ap_sync_done : STD_LOGIC;
    signal ap_sync_ready : STD_LOGIC;
    signal loop_dataflow_input_count : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal loop_dataflow_output_count : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal bound_minus_1 : STD_LOGIC_VECTOR (4 downto 0);
    signal dataflow_in_loop_lst_U0_start_full_n : STD_LOGIC;
    signal dataflow_in_loop_lst_U0_start_write : STD_LOGIC;

    component dataflow_in_loop_lst IS
    port (
        img_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        img_ce0 : OUT STD_LOGIC;
        img_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        img_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        img_we0 : OUT STD_LOGIC;
        img_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        img_ce1 : OUT STD_LOGIC;
        img_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        img_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        img_we1 : OUT STD_LOGIC;
        i1 : IN STD_LOGIC_VECTOR (4 downto 0);
        h_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        h_ce0 : OUT STD_LOGIC;
        h_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        h_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        h_we0 : OUT STD_LOGIC;
        h_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
        h_ce1 : OUT STD_LOGIC;
        h_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        h_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        h_we1 : OUT STD_LOGIC;
        c_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        c_ce0 : OUT STD_LOGIC;
        c_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        c_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        c_we0 : OUT STD_LOGIC;
        c_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
        c_ce1 : OUT STD_LOGIC;
        c_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        c_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        c_we1 : OUT STD_LOGIC;
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        i1_ap_vld : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    dataflow_in_loop_lst_U0 : component dataflow_in_loop_lst
    port map (
        img_address0 => dataflow_in_loop_lst_U0_img_address0,
        img_ce0 => dataflow_in_loop_lst_U0_img_ce0,
        img_d0 => dataflow_in_loop_lst_U0_img_d0,
        img_q0 => img_q0,
        img_we0 => dataflow_in_loop_lst_U0_img_we0,
        img_address1 => dataflow_in_loop_lst_U0_img_address1,
        img_ce1 => dataflow_in_loop_lst_U0_img_ce1,
        img_d1 => dataflow_in_loop_lst_U0_img_d1,
        img_q1 => ap_const_lv32_0,
        img_we1 => dataflow_in_loop_lst_U0_img_we1,
        i1 => loop_dataflow_input_count,
        h_address0 => dataflow_in_loop_lst_U0_h_address0,
        h_ce0 => dataflow_in_loop_lst_U0_h_ce0,
        h_d0 => dataflow_in_loop_lst_U0_h_d0,
        h_q0 => h_q0,
        h_we0 => dataflow_in_loop_lst_U0_h_we0,
        h_address1 => dataflow_in_loop_lst_U0_h_address1,
        h_ce1 => dataflow_in_loop_lst_U0_h_ce1,
        h_d1 => dataflow_in_loop_lst_U0_h_d1,
        h_q1 => ap_const_lv32_0,
        h_we1 => dataflow_in_loop_lst_U0_h_we1,
        c_address0 => dataflow_in_loop_lst_U0_c_address0,
        c_ce0 => dataflow_in_loop_lst_U0_c_ce0,
        c_d0 => dataflow_in_loop_lst_U0_c_d0,
        c_q0 => c_q0,
        c_we0 => dataflow_in_loop_lst_U0_c_we0,
        c_address1 => dataflow_in_loop_lst_U0_c_address1,
        c_ce1 => dataflow_in_loop_lst_U0_c_ce1,
        c_d1 => dataflow_in_loop_lst_U0_c_d1,
        c_q1 => ap_const_lv32_0,
        c_we1 => dataflow_in_loop_lst_U0_c_we1,
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        i1_ap_vld => ap_const_logic_0,
        ap_start => dataflow_in_loop_lst_U0_ap_start,
        ap_done => dataflow_in_loop_lst_U0_ap_done,
        ap_ready => dataflow_in_loop_lst_U0_ap_ready,
        ap_idle => dataflow_in_loop_lst_U0_ap_idle,
        ap_continue => dataflow_in_loop_lst_U0_ap_continue);





    loop_dataflow_input_count_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                loop_dataflow_input_count <= ap_const_lv5_0;
            else
                if ((not((loop_dataflow_input_count = bound_minus_1)) and (ap_start = ap_const_logic_1) and (dataflow_in_loop_lst_U0_ap_ready = ap_const_logic_1))) then 
                    loop_dataflow_input_count <= std_logic_vector(unsigned(loop_dataflow_input_count) + unsigned(ap_const_lv5_1));
                elsif (((loop_dataflow_input_count = bound_minus_1) and (ap_start = ap_const_logic_1) and (dataflow_in_loop_lst_U0_ap_ready = ap_const_logic_1))) then 
                    loop_dataflow_input_count <= ap_const_lv5_0;
                end if; 
            end if;
        end if;
    end process;


    loop_dataflow_output_count_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                loop_dataflow_output_count <= ap_const_lv5_0;
            else
                if ((not((loop_dataflow_output_count = bound_minus_1)) and (dataflow_in_loop_lst_U0_ap_continue = ap_const_logic_1) and (dataflow_in_loop_lst_U0_ap_done = ap_const_logic_1))) then 
                    loop_dataflow_output_count <= std_logic_vector(unsigned(loop_dataflow_output_count) + unsigned(ap_const_lv5_1));
                elsif (((loop_dataflow_output_count = bound_minus_1) and (dataflow_in_loop_lst_U0_ap_continue = ap_const_logic_1) and (dataflow_in_loop_lst_U0_ap_done = ap_const_logic_1))) then 
                    loop_dataflow_output_count <= ap_const_lv5_0;
                end if; 
            end if;
        end if;
    end process;


    ap_done_assign_proc : process(dataflow_in_loop_lst_U0_ap_done, loop_dataflow_output_count, bound_minus_1)
    begin
        if (((loop_dataflow_output_count = bound_minus_1) and (dataflow_in_loop_lst_U0_ap_done = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_idle <= dataflow_in_loop_lst_U0_ap_idle;

    ap_ready_assign_proc : process(dataflow_in_loop_lst_U0_ap_ready, ap_start, loop_dataflow_input_count, bound_minus_1)
    begin
        if (((loop_dataflow_input_count = bound_minus_1) and (ap_start = ap_const_logic_1) and (dataflow_in_loop_lst_U0_ap_ready = ap_const_logic_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_sync_continue <= ap_continue;
    ap_sync_done <= dataflow_in_loop_lst_U0_ap_done;
    ap_sync_ready <= dataflow_in_loop_lst_U0_ap_ready;
    bound_minus_1 <= std_logic_vector(unsigned(ap_const_lv5_1C) - unsigned(ap_const_lv5_1));
    c_address0 <= dataflow_in_loop_lst_U0_c_address0;
    c_address1 <= ap_const_lv7_0;
    c_ce0 <= dataflow_in_loop_lst_U0_c_ce0;
    c_ce1 <= ap_const_logic_0;
    c_d0 <= dataflow_in_loop_lst_U0_c_d0;
    c_d1 <= ap_const_lv32_0;
    c_we0 <= dataflow_in_loop_lst_U0_c_we0;
    c_we1 <= ap_const_logic_0;

    dataflow_in_loop_lst_U0_ap_continue_assign_proc : process(ap_continue, loop_dataflow_output_count, bound_minus_1)
    begin
        if ((not((loop_dataflow_output_count = bound_minus_1)) or (ap_continue = ap_const_logic_1))) then 
            dataflow_in_loop_lst_U0_ap_continue <= ap_const_logic_1;
        else 
            dataflow_in_loop_lst_U0_ap_continue <= ap_const_logic_0;
        end if; 
    end process;

    dataflow_in_loop_lst_U0_ap_start <= ap_start;
    dataflow_in_loop_lst_U0_start_full_n <= ap_const_logic_1;
    dataflow_in_loop_lst_U0_start_write <= ap_const_logic_0;
    h_address0 <= dataflow_in_loop_lst_U0_h_address0;
    h_address1 <= ap_const_lv7_0;
    h_ce0 <= dataflow_in_loop_lst_U0_h_ce0;
    h_ce1 <= ap_const_logic_0;
    h_d0 <= dataflow_in_loop_lst_U0_h_d0;
    h_d1 <= ap_const_lv32_0;
    h_we0 <= dataflow_in_loop_lst_U0_h_we0;
    h_we1 <= ap_const_logic_0;
    img_address0 <= dataflow_in_loop_lst_U0_img_address0;
    img_address1 <= ap_const_lv10_0;
    img_ce0 <= dataflow_in_loop_lst_U0_img_ce0;
    img_ce1 <= ap_const_logic_0;
    img_d0 <= ap_const_lv32_0;
    img_d1 <= ap_const_lv32_0;
    img_we0 <= ap_const_logic_0;
    img_we1 <= ap_const_logic_0;
end behav;
