// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _dense_forward_HH_
#define _dense_forward_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "top_fadd_32ns_32nAem.h"
#include "top_fmul_32ns_32nBew.h"
#include "top_fcmp_32ns_32nEe0.h"
#include "dense_forward_denHfu.h"
#include "dense_forward_denIfE.h"

namespace ap_rtl {

struct dense_forward : public sc_module {
    // Port declarations 14
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<7> > h_address0;
    sc_out< sc_logic > h_ce0;
    sc_in< sc_lv<32> > h_q0;
    sc_out< sc_lv<7> > dense_output_address0;
    sc_out< sc_logic > dense_output_ce0;
    sc_out< sc_logic > dense_output_we0;
    sc_out< sc_lv<32> > dense_output_d0;
    sc_in< sc_lv<32> > dense_output_q0;
    sc_signal< sc_logic > ap_var_for_const0;
    sc_signal< sc_lv<32> > ap_var_for_const1;
    sc_signal< sc_lv<5> > ap_var_for_const2;


    // Module declarations
    dense_forward(sc_module_name name);
    SC_HAS_PROCESS(dense_forward);

    ~dense_forward();

    sc_trace_file* mVcdFile;

    dense_forward_denHfu* dense_kernel_U;
    dense_forward_denIfE* dense_bias_U;
    top_fadd_32ns_32nAem<1,4,32,32,32>* top_fadd_32ns_32nAem_U33;
    top_fmul_32ns_32nBew<1,3,32,32,32>* top_fmul_32ns_32nBew_U34;
    top_fcmp_32ns_32nEe0<1,1,32,32,1>* top_fcmp_32ns_32nEe0_U35;
    sc_signal< sc_lv<18> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<14> > dense_kernel_address0;
    sc_signal< sc_logic > dense_kernel_ce0;
    sc_signal< sc_lv<32> > dense_kernel_q0;
    sc_signal< sc_lv<7> > dense_bias_address0;
    sc_signal< sc_logic > dense_bias_ce0;
    sc_signal< sc_lv<32> > dense_bias_q0;
    sc_signal< sc_lv<32> > grp_fu_141_p2;
    sc_signal< sc_lv<32> > reg_155;
    sc_signal< sc_logic > ap_CS_fsm_state11;
    sc_signal< sc_logic > ap_CS_fsm_state17;
    sc_signal< sc_lv<8> > i_24_fu_167_p2;
    sc_signal< sc_lv<8> > i_24_reg_293;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<16> > tmp_cast_fu_178_p1;
    sc_signal< sc_lv<16> > tmp_cast_reg_298;
    sc_signal< sc_lv<1> > exitcond2_fu_161_p2;
    sc_signal< sc_lv<7> > dense_output_addr_reg_303;
    sc_signal< sc_lv<8> > j_11_fu_188_p2;
    sc_signal< sc_lv<8> > j_11_reg_311;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<1> > exitcond1_fu_182_p2;
    sc_signal< sc_lv<32> > dense_kernel_load_reg_326;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<32> > h_load_reg_331;
    sc_signal< sc_lv<32> > grp_fu_146_p2;
    sc_signal< sc_lv<32> > tmp_108_reg_336;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<8> > i_25_fu_227_p2;
    sc_signal< sc_lv<8> > i_25_reg_344;
    sc_signal< sc_logic > ap_CS_fsm_state12;
    sc_signal< sc_lv<1> > exitcond_fu_221_p2;
    sc_signal< sc_lv<7> > dense_output_addr_1_reg_354;
    sc_signal< sc_lv<32> > dense_bias_load_reg_359;
    sc_signal< sc_logic > ap_CS_fsm_state13;
    sc_signal< sc_lv<32> > dense_output_load_reg_364;
    sc_signal< sc_lv<8> > i_reg_95;
    sc_signal< sc_lv<32> > storemerge1_reg_106;
    sc_signal< sc_lv<8> > j_reg_119;
    sc_signal< sc_lv<8> > i1_reg_130;
    sc_signal< sc_logic > ap_CS_fsm_state18;
    sc_signal< sc_lv<64> > tmp_fu_173_p1;
    sc_signal< sc_lv<64> > tmp_163_cast_fu_216_p1;
    sc_signal< sc_lv<64> > tmp_107_fu_194_p1;
    sc_signal< sc_lv<64> > tmp_105_fu_233_p1;
    sc_signal< sc_lv<32> > storemerge_fu_281_p3;
    sc_signal< sc_lv<32> > grp_fu_141_p0;
    sc_signal< sc_lv<32> > grp_fu_141_p1;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_logic > ap_CS_fsm_state14;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<15> > tmp_149_fu_199_p3;
    sc_signal< sc_lv<16> > tmp_162_cast_fu_207_p1;
    sc_signal< sc_lv<16> > tmp_151_fu_211_p2;
    sc_signal< sc_lv<32> > tmp_106_to_int_fu_239_p1;
    sc_signal< sc_lv<8> > tmp_145_fu_243_p4;
    sc_signal< sc_lv<23> > tmp_150_fu_253_p1;
    sc_signal< sc_lv<1> > notrhs_fu_263_p2;
    sc_signal< sc_lv<1> > notlhs_fu_257_p2;
    sc_signal< sc_lv<1> > tmp_s_fu_269_p2;
    sc_signal< sc_lv<1> > tmp_147_fu_150_p2;
    sc_signal< sc_lv<1> > tmp_148_fu_275_p2;
    sc_signal< sc_lv<18> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<18> ap_ST_fsm_state1;
    static const sc_lv<18> ap_ST_fsm_state2;
    static const sc_lv<18> ap_ST_fsm_state3;
    static const sc_lv<18> ap_ST_fsm_state4;
    static const sc_lv<18> ap_ST_fsm_state5;
    static const sc_lv<18> ap_ST_fsm_state6;
    static const sc_lv<18> ap_ST_fsm_state7;
    static const sc_lv<18> ap_ST_fsm_state8;
    static const sc_lv<18> ap_ST_fsm_state9;
    static const sc_lv<18> ap_ST_fsm_state10;
    static const sc_lv<18> ap_ST_fsm_state11;
    static const sc_lv<18> ap_ST_fsm_state12;
    static const sc_lv<18> ap_ST_fsm_state13;
    static const sc_lv<18> ap_ST_fsm_state14;
    static const sc_lv<18> ap_ST_fsm_state15;
    static const sc_lv<18> ap_ST_fsm_state16;
    static const sc_lv<18> ap_ST_fsm_state17;
    static const sc_lv<18> ap_ST_fsm_state18;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<8> ap_const_lv8_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_11;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<8> ap_const_lv8_80;
    static const sc_lv<8> ap_const_lv8_1;
    static const sc_lv<7> ap_const_lv7_0;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<32> ap_const_lv32_1E;
    static const sc_lv<8> ap_const_lv8_FF;
    static const sc_lv<23> ap_const_lv23_0;
    static const sc_lv<5> ap_const_lv5_4;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_var_for_const1();
    void thread_ap_var_for_const2();
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state12();
    void thread_ap_CS_fsm_state13();
    void thread_ap_CS_fsm_state14();
    void thread_ap_CS_fsm_state17();
    void thread_ap_CS_fsm_state18();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_dense_bias_address0();
    void thread_dense_bias_ce0();
    void thread_dense_kernel_address0();
    void thread_dense_kernel_ce0();
    void thread_dense_output_address0();
    void thread_dense_output_ce0();
    void thread_dense_output_d0();
    void thread_dense_output_we0();
    void thread_exitcond1_fu_182_p2();
    void thread_exitcond2_fu_161_p2();
    void thread_exitcond_fu_221_p2();
    void thread_grp_fu_141_p0();
    void thread_grp_fu_141_p1();
    void thread_h_address0();
    void thread_h_ce0();
    void thread_i_24_fu_167_p2();
    void thread_i_25_fu_227_p2();
    void thread_j_11_fu_188_p2();
    void thread_notlhs_fu_257_p2();
    void thread_notrhs_fu_263_p2();
    void thread_storemerge_fu_281_p3();
    void thread_tmp_105_fu_233_p1();
    void thread_tmp_106_to_int_fu_239_p1();
    void thread_tmp_107_fu_194_p1();
    void thread_tmp_145_fu_243_p4();
    void thread_tmp_148_fu_275_p2();
    void thread_tmp_149_fu_199_p3();
    void thread_tmp_150_fu_253_p1();
    void thread_tmp_151_fu_211_p2();
    void thread_tmp_162_cast_fu_207_p1();
    void thread_tmp_163_cast_fu_216_p1();
    void thread_tmp_cast_fu_178_p1();
    void thread_tmp_fu_173_p1();
    void thread_tmp_s_fu_269_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
